### PR TITLE
Entity system rework

### PR DESCRIPTION
**Pull request by L3nn0x**
This solves the factory instanciation error and the entity access after destroy. It also sanitizes CMapClient access from an entity system.

---
This change is [Reviewable](https://reviewable.io/reviews/dev-osrose/osirose-new/110)

### CODE REVIEW

**Comment by L3nn0x** [comment]
solves #95

**Comment by RavenX8** [comment]
Reviewed 71 of 71 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/char/src/ccharclient.cpp, line 66 at r1](https://reviewable.io:443/reviews/dev-osrose/osirose-new/110#-KsVdw6G8exZTfrEdiNT:-KsVdw6Hce2qglUHM5_6:b-jzmla6) ([raw file](https://github.com/dev-osrose/osirose-new/blob/4c5d011f5920ad1d648e0e1eff9771f3870a757c/src/char/src/ccharclient.cpp#L66)):*
> ```cpp
>           getPacket<ePacketType::PAKCS_SELECT_CHAR_REQ>(_buffer));
>     default:
>       CRoseClient::HandlePacket(_buffer);
> ```

Why was the return removed here?

---

*[src/map/include/cmapclient.h, line 30 at r1](https://reviewable.io:443/reviews/dev-osrose/osirose-new/110#-KsVeKgQVN2IvqGNyzIK:-KsVeKgQVN2IvqGNyzIL:bz6u630) ([raw file](https://github.com/dev-osrose/osirose-new/blob/4c5d011f5920ad1d648e0e1eff9771f3870a757c/src/map/include/cmapclient.h#L30)):*
> ```objc
> }
> 
> class CMapClient : public RoseCommon::CRoseClient, public std::enable_shared_from_this<CMapClient> {
> ```

What is std::enable_shared_from_this? Never seen this before. Not an issue, I just want to know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dev-osrose/osirose-new/110)*

**Comment by L3nn0x** [comment]
std::enable_shared_from_this allows an instance of the class to generate shared_ptr to this if it is already referenced in a shared_ptr elsewhere. The new shared_ptr will correctly correspond to the already existing shared_ptr of this instance.

**Comment by L3nn0x** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/char/src/ccharclient.cpp, line 66 at r1](https://reviewable.io:443/reviews/dev-osrose/osirose-new/110#-KsVdw6G8exZTfrEdiNT:-KsdnpvfTlXgI8smLI3E:b-lw5u8h) ([raw file](https://github.com/dev-osrose/osirose-new/blob/4c5d011f5920ad1d648e0e1eff9771f3870a757c/src/char/src/ccharclient.cpp#L66)):*
<details><summary><i>Previously, RavenX8 (Christopher Torres) wrote…</i></summary><blockquote>

Why was the return removed here?
</blockquote></details>

The return was removed because some packets aren't supported by the char server yet, and I don't want the char server to close the connection to the client.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dev-osrose/osirose-new/110)*

**Pull request merged**
