### PR TITLE
Temporarily disable appveyor builds

### PR DESCRIPTION
**Pull request by rminderhoud**
Temporarily disable appveyor builds since they were failing and msys will not be supported.

This change is [Reviewable](https://reviewable.io/reviews/dev-osrose/osirose-new/175)

### CODE REVIEW

**Review by L3nn0x — COMMENTED** [review]
lgtm but I want raven to sign this one off. He's the one maintaining the build system

**Comment by RavenX8** [comment]
I would have to say no to this. I'd rather add the builds as allow failures. That way we can tell when the toolset is fixed

**Review by RavenX8 — CHANGES_REQUESTED** [review]
instead of disabling it, just set it to allow failures

**Comment by rminderhoud** [comment]
Is this all that's required to do the msvc build `cmd: "%PROJECT_PATH%/cmake/scripts/msvc_build.bat"`? I think we can at least get rid of the msys build.

**Comment by rminderhoud** [comment]
Allowed failures for `Visual studio 2017` image

**Comment by RavenX8** [comment]
This isn't needed once basic_attack is merged

**Pull request closed without merging**
